routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware'=>'auth'],function(){
		Route::get('/', function () {
    		return redirect('/');
		});
		Route::get('/','keepController@front');

		
		// Route::post('/notebooks','keepController@store');
		// Route::get('/notebooks/create','keepController@create');
		// Route::get('/notebooks/{notebooks}','keepController@show')->name('notebooks.show');		
		// Route::get('/notebooks/{notebooks}/edit','keepController@edit')->name('notebooks.edit');
		// Route::put('/notebooks/{notebooks}','keepController@update');
		// Route::delete('/notebooks/{notebooks}','keepController@destroy');

		Route::resource('notebooks','keepController');
		Route::resource('notes','NotesController');


		Route::get('notes/{notebookId}/createNote','NotesController@createNote')->name('notes.createNote');
});

// Route::get('/keep','keepController@index');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/Note.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    protected $fillable=['title','body','notebook_id'];

    public function notebook()
    {
    	return $this->belongsTo(Notebook::class);
    }
}

app/Notebook.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notebook extends Model
{
	protected $connection = 'pgsql';

	protected $table = 'note';

	protected $fillable=['name'];

	public function notes()
	{
		return $this->hasMany(Note::class);
	}
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function notebooks()
    {
        return $this->hasMany(Notebook::class);
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/NotesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Note;

class NotesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $inputData= $request->all();

        Note::create($inputData);

        $notebookId= $request->notebook_id;

        // return redirect()->route('notebook.index');
        return redirect()->route('notebooks.show', compact('notebookId'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $note=Note::find($id);
        return view('notes.show',compact('note'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $note = Note::find($id);
        return view('notes.edit', compact('note'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $inputData= $request->all();

        $note= Note::find($id);
        $note->update($inputData);

        return redirect()->route('notebooks.show',$note->notebookId);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Note::destroy($id);
        return back();
    }

    public function createNote($notebookId)
    {
        return view('notes.create')->with('id',$notebookId);
    }
}

app/Http/Controllers/keepController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Routing\Controller as BaseController;
use App\Notebook;
use Illuminate\Http\Request;
/**
* 
*/
class keepController extends BaseController
{
	
	// function index()
	// {
	// 	return view('keep\index');
	// }

	function front()
	{
		return view('.frontpage');
	}

	public function index()
	{
		$user= Auth::user();
		$note=$user->notebooks;

    	return view('notebooks.index', compact('note'));
	}

	public function create()
	{
		return view('notebooks.create');
	}

	public function show($id)
	{
		$note= Notebook::findOrFail($id);
		$notes= $note->notes;
		return view('notes.index',compact('notes','note'));
	}

	public function store(Request $request)
	{
		$dataInput=$request->all();
		$user=Auth::user();
		$user->notebooks()->create($dataInput);
		// Notebook::create($dataInput);

		//return "berhasil";
		return redirect('/notebooks');
	}

	public function edit($id)
	{
		$user= Auth::user();
		$note= $user->notebooks()->find($id);
		// $note=Notebook::where('id',$id)->first();
		return view('notebooks.edit')->with('notebook',$note);
	}

	public function update(Request $request,$id)
	{
		// $note=Notebook::where('id',$id)->first();
		$user= Auth::user();
		$note= $user->notebooks()->find($id);

		$note->update($request->all());

		return redirect('/notebooks');
	}

	public function destroy($id)
	{
		// $note=Notebook::where('id',$id)->first();
		$user= Auth::user();
		$note= $user->notebooks()->find($id);

		$note->delete();
		return redirect('/notebooks');
	}
}

resources/views/frontpage.blade.php
@extends('layouts.base')


@section('content')
        <!-- Main component for call to action -->
        <div class="jumbotron">
            <h1>Notebook</h1>
            <p>Store and organise your thoughts in notebook and NoteBook web app makes this easier than ever</p>
            <p>
                <a class="btn btn-lg btn-primary" href="{{route('notebooks.index')}}" role="button">Your NoteBooks</a>
            </p>
        </div>
    </div>
    <!-- /container -->
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/keep/keep.blade.php
<html>

	<head>
		<title>Gokeep</title>
		
		<script src="js/layout.js"></script>
		<noscript>
			<link rel="stylesheet" href="css/layout.css"/>
		</noscript>
	</head>

	<body>
		<div class="notes" style="position: relative; height: 1238px";>
			<div class="notes" style="position: absolute; left: 0px; top: 0px"> 
				<div class="note-inner" style="height: 310px"></div>
			</div>
		</div>

		<button class="big-add show-add-note"><i class="material-icons">add</i></button>
	</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>NoteBook App</title>
    <link rel="stylesheet" href="{{asset('dist/css/main.css')}}">
    <link rel="stylesheet" href="{{asset('dist/css/bootstrap.css')}}">
</head>

<body>
    <div class="container-fluid">
        <nav class="navbar  navbar-dark bg-primary">
            <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header">
                &#9776;
            </button>
            <div class="collapse navbar-toggleable-xs" id="navbar-header">
                <a class="navbar-brand" href="#">NoteBook App</a>
            </div>

            <ul class="dropdown">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle namadropdown" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
            <!-- @if(Auth::user())
                <li>{{Auth::user()->name}}</li>

                @else
                <a href="/login">Login</a><br>
                <a href="/register">Register</a>

            @endif -->
        </nav>
        <!-- /navbar -->
        <!-- Main component for call to action -->
        @yield('content')
    </div>
    <!-- /container -->

    <script src="{{asset('dist/js/jquery3.min.js')}}"></script>
    <script src="{{asset('dist/js/bootstrap.js')}}"></script>
</body>

</html>

resources/views/notebooks/create.blade.php
@extends('layouts.base')

@section('content')

<div class="container">
	<h1>Create Notebook</h1>

<form action="/notebooks" method="POST">
{{csrf_field()}}
<div class="form-group">

	<label for="name">Notebook name</label>
	<input class="form-control" type="text" name="name">

</div>	
	<input class="btn btn-primary" type="submit" value="Done">		
	</input>
</form>

</div>
@endsection

resources/views/notebooks/edit.blade.php
@extends('layouts.base')

@section('content')

<div class="container">
	<h1>Edit Notebook</h1>

<form action="/notebooks/{{$notebook->id}}" method="POST">
{{csrf_field()}}
{{method_field('PUT')}}
<div class="form-group">

	<label for="name">Notebook name</label>
	<input class="form-control" type="text" name="name">

</div>	
	<input class="btn btn-primary" type="submit" value="update">		
	</input>
</form>

</div>
@endsection

resources/views/notebooks/index.blade.php
@extends('layouts.base')

@section('content')
            <!-- Main component for call to action -->
            <div class="container text-center">
                <!-- heading -->
                <h1 class="pull-xs-left">
                    Your Notebooks
                </h1>
                <div class="pull-xs-right">
                    <a class="btn btn-primary" href="/notebooks/create" role="button">
                        New NoteBook +
                    </a>
                </div>

                <div class="clearfix">
                </div>
                <br>
                
                <!-- ================ Notebooks==================== -->
                <!-- notebook1 -->

                @foreach ($note as $notebook)                                    

                <div class="col-sm-6 col-md-3">
                    <div class="card">
                        <div class="card-block">
                            <a href="{{route("notebooks.show",$notebook->id)}}">
                                <h4 class="card-title">
                                    {{$notebook->name}}
                                </h4>
                            </a>
                        </div>
                        <a href="#">
                            <img alt="Responsive image" class="img-fluid" src="dist/img/notebook.jpg"/>
                        </a>
                        <div class="card-block">
                            <a class="card-link" href="{{route("notebooks.edit",$notebook->id)}}"> <!-- /notebooks/{{$notebook->id}} -->
                                Edit Notebook
                            </a>
                            <form action="/notebooks/{{$notebook->id}}" class="pull-xs-right5 card-link" method="POST" style="display:inline">
                            {{csrf_field()}}
                            {{method_field('DELETE')}}
                                <input class="btn btn-sm btn-danger" type="submit" value="Delete">
                            
                            
                                
                            </form>
                        </div>
                    </div>
                </div>

                @endforeach
                    
            </div>
            <!-- /container -->
@endsection

resources/views/notes/create.blade.php
@extends('layouts.base')

@section('content')

<div class="container">
	<h1>Buat Catatan</h1>

<form action="{{route('notes.store')}}" method="POST">
{{csrf_field()}}
<div class="form-group">

	<label for="title">Judul Catatan</label>
	<input class="form-control" type="text" name="title">

</div>	
<div class="form-group">

	<label for="body">Isi Catatan</label>
	<input class="form-control" type="text" name="body">

</div>
	<input type="hidden" name="notebook_id" value="{{$id}}">

	<input class="btn btn-primary" type="submit" value="Done">		
	</input>
</form>

</div>
@endsection

resources/views/notes/edit.blade.php
@extends('layouts.base')

@section('content')

<div class="container">
	<h1>Edit Catatan</h1>

<form action="{{route('notes.update',$note->id)}}" method="POST">
{{csrf_field()}}
{{method_field('PUT')}}
<div class="form-group">

	<label for="title">Judul Catatan</label>
	<input class="form-control" type="text" name="title" value="{{$note->title}}">

</div>	
<div class="form-group">

	<label for="body">Isi Catatan</label>
	<input class="form-control" type="text" name="body" value="{{$note->body}}">

</div>


	<input class="btn btn-primary" type="submit" value="Done">		
	</input>
</form>

</div>
@endsection

resources/views/notes/index.blade.php
@extends('layouts.base')

@section('content')
            <!-- Main component for call to action -->
            <div class="container">
                <h1 class="pull-xs-left">
                    Notes
                </h1>
                <div class="pull-xs-right">
                    <a class="btn btn-primary" href="{{route('notes.createNote',$note->id)}}" role="button">
                        New Note +
                    </a>
                </div>
                <div class="clearfix">
                </div>
                <!--============= notes=========== -->
                <div class="list-group notes-group">

                    <!--note1 -->
                    @foreach($notes as $note)
                    <div class="card card-block">
                        <a href="{{route('notes.show',$note->id)}}">
                            <h4 class="card-title">
                                {{$note->title}}
                            </h4>
                        </a>
                        <p class="card-text">
                            {{$note->body}}
                        </p>
                        <a class="btn btn-sm btn-info pull-xs-left" href="{{route('notes.edit',$note->id)}}">
                            Edit
                        </a>
                        <form action="{{route('notes.destroy',$note->id)}}" class="pull-xs-right" method="POST">
                        {{csrf_field()}}
                        {{method_field('DELETE')}}
                            <input class="btn btn-sm btn-danger" type="submit" value="Delete">
                            
                        </form>
                    </div>
                    @endforeach

                </div>
            </div>
            <!-- /container -->

@endsection

resources/views/notes/show.blade.php
@extends('layouts.base')

@section('content')

	<div class="container">

		<div class="row">

			<h3 class="display-3">
				{{$note->title}}
			</h3>

			<p>
				{{$note->body}}
			</p>

		</div>

	</div>

@endsection